name: Exhaust
favicon: null
layout_spectrum: 0.5102627433370799
typography_spectrum: 0.23455956391990185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5254910378716886
  lightness: 0.4224380187224597
  saturation: 0.2984245989937335
  rhythmicContrast: 0.40766161447390914
purpose: []
